require 'minitest/autorun'
require 'minitest'

require_relative 'tc_board'
require_relative 'tc_cell'
#require_relative 'tc_http_client'
require_relative 'tc_parchis'
require_relative 'tc_player'
require_relative 'tc_token'
require_relative 'tc_dice'
require_relative 'tc_game_state_updater'
require_relative 'tc_lobby_updater'
require_relative 'tc_seven_faces_dice'
require_relative 'tc_six_faces_dice'
require_relative 'tc_v_actions'
require_relative 'tc_v_countdown'
require_relative 'tc_v_current_turn'
require_relative 'tc_v_stats'
require_relative 'tc_v_tips'
require_relative 'tc_v_widget'
require_relative 'tc_delayer'


